### ISSUE TITLE
Example readabililty

### ISSUE THREAD

**Issue by gilcot** [Namburger/restor#1]
About the example in the README.md
> `$  echo "{\"detector\":\"please\", \"data\":\"``cat test_data/grace_hopper.bmp|base64 -w0``\"}" > /tmp/grace.json && curl -d@/tmp/grace.json -H "Content-Type: application/json" -X POST http://localhost:8888/detects | jq `

I think that first line should be split so: 
```
$ # create the JSON file with BMP encoded data
$  cat >/tmp/grace.json <<<EOF
{"detector":"please", "data":" $(
  cat test_data/grace_hopper.bmp |
  base64 -w0
)"}
EOF
$ # if no error, submit that JSON file
$ curl -d@/tmp/grace.json \
  -H "Content-Type: application/json" \
  -X POST \
  http://localhost:8888/detects | 
jq
```

**Comment by Namburger** [comment]
@gilcot Thanks, will consider, the idea was that I wanted a one liner, but may add an explanation section below.
